---
name: Bug Report
description: Create a Report to Help us Improve
labels:
  - bug
body:
  - id: bug_details
    type: textarea
    attributes:
      label: Bug Details
      description: |
        Please provide the following information about the bug:
        1. **Description:** What is the bug?
        2. **To Reproduce:** Minimal code example to reproduce the issue.
        3. **Expected Behaviour:** What you expected to happen.
        4. **Actual Behaviour:** What actually happened, include errors or stack traces.
      placeholder: |
        Description: 

        To Reproduce:
        ```python
        import udetect
        ...
        ```

        Expected Behaviour: 

        Actual Behaviour: 
    validations:
      required: true

  - id: context
    type: textarea
    attributes:
      label: Environment & Additional Context
      description: |
        Please provide version and any other context about your environment.
      placeholder: |
        Version in Use: 

        Python Version: 

        Operating System: 

        Additional Context: 
