---
name: Feature Request
description: Suggest a Way to Improve This Project
labels:
  - enhancement
body:
  - id: feature_request
    type: textarea
    attributes:
      label: Feature Request Details
      description: |
        Please provide the following information in one response:
        1. **Problem:** Describe the problem you're experiencing.
        2. **Solution:** Describe the solution you'd like.
        3. **Alternatives:** Describe any alternatives you've considered.
        4. **Additional Context:** Add any other context or screenshots here.
      placeholder: |
        Problem: I'm always frustrated when [...]

        Solution: I would like [...]

        Alternatives: I considered [...]

        Additional Context: [...]
    validations:
      required: true