ARG UBUNTU_RELEASE_YEAR=24
ARG UBUNTU_RELEASE_MONTH=04
ARG CUDA_MAJOR=13
ARG CUDA_MINOR=0
ARG CUDA_PATCH=0

# Ubuntu versions
##  Ubuntu 24.04 Noble
##  Ubuntu 22.04 Jammy

# General ROS2 environment variables
# Define the container image(s) associated with each ROS distribution.
# Platforms are defined in REP 2000: https://ros.org/reps/rep-2000.html
##  Humble Hawksbill (May 2022 - May 2027); Ubuntu 22.04; python3.10
##  Iron Irwini (May 2023 - November 2024)
##  Jazzy Jalisco (May 2024 - May 2029);  Ubuntu 24.04; python3.12

# Gazebo versions
## Gz Jetty > ROS 2 Rolling
## Gz Ionic > ROS 2 Kilted
## GZ Fortress (LTS) > ROS 2 Humble (LTS)
## GZ Harmonic (LTS) > ROS 2 Jazzy (LTS)
## https://gazebosim.org/docs/latest/ros_installation/

FROM docker.io/nvidia/cuda:${CUDA_MAJOR}.${CUDA_MINOR}.${CUDA_PATCH}-devel-ubuntu${UBUNTU_RELEASE_YEAR}.${UBUNTU_RELEASE_MONTH} AS base
#Latest cuda image versions https://hub.docker.com/r/nvidia/cuda/tags

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV ACCEPT_EULA=Y
ENV PRIVACY_CONSENT=Y
ENV LANG=en_GB.UTF-8
ENV LC_ALL=en_GB.UTF-8
ARG USERNAME=root
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,video,utility,graphics

# Qt Base Configuration
ENV QT_X11_NO_MITSHM=1
ENV QT_DEBUG_PLUGINS=0

# For GUI applications (requires X11 forwarding or virtual display)
ENV DISPLAY=:0
ENV QT_QPA_PLATFORM=xcb

# Plugin paths (adjust based on your Qt installation)
# ENV QT_PLUGIN_PATH=/opt/qt/plugins
# ENV QT_QPA_PLATFORM_PLUGIN_PATH=/opt/qt/plugins/platforms



# Timezone Europe/London
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
RUN echo "CUDA Version ${CUDA_MAJOR}.${CUDA_MINOR}.${CUDA_PATCH}" > /usr/local/cuda/version.txt

# Language
RUN apt-get update && apt-get install -y locales
RUN locale-gen en_GB ${LANG}
RUN update-locale LC_ALL=${LC_ALL} LANG=${LANG}

#####################################
# Installing and setting up ROS2
#####################################

# Setup the sources
RUN apt-get update -qq && apt-get install -y software-properties-common curl && \
    add-apt-repository universe && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Setup gazebosim transport
RUN curl -sSL https://packages.osrfoundation.org/gazebo.key | gpg --dearmor -o /usr/share/keyrings/gazebo-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gazebo-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list && \
    apt-get update -qq && \
    apt-get install -y libgz-transport13-dev

#ENV ROS_DISTRO=humble
ENV ROS_DISTRO=jazzy
ENV PYTHON_VERSION=python3.12

ENV ROS_VERSION=2
ENV ROS_PYTHON_VERSION=3
ENV AMENT_PREFIX_PATH=/opt/ros/${ROS_DISTRO}
ENV COLCON_PREFIX_PATH=/opt/ros/${ROS_DISTRO}
ENV LD_LIBRARY_PATH=/opt/ros/${ROS_DISTRO}/lib
ENV PATH=/opt/ros/${ROS_DISTRO}/bin:$PATH
ENV PYTHONPATH=/opt/ros/${ROS_DISTRO}/lib/${PYTHON_VERSION}/site-packages


# Install ROS 2 packages
RUN apt-get update -qq && apt-get upgrade -y && \
    apt-get install -y \
    ros-${ROS_DISTRO}-desktop \
    ros-${ROS_DISTRO}-turtlesim \
    ros-${ROS_DISTRO}-rqt* \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-ros-gz \
    ros-${ROS_DISTRO}-gz-ros2-control \
    ros-${ROS_DISTRO}-ros2-control \
    ros-${ROS_DISTRO}-ros2-controllers \
    ros-${ROS_DISTRO}-controller-manager \
    ros-${ROS_DISTRO}-controller-manager-msgs \
    ros-${ROS_DISTRO}-joint-state-broadcaster \
    ros-${ROS_DISTRO}-forward-command-controller \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    bash-completion \
    cmake \
    gdb \
    git \
    git-core \
    gnupg2 \
    openssh-client \
    file \
    tree \
    lsb-release \
    wget \
    less \
    udev \
    sudo \
    gfortran \
    libpng-dev \
    libgomp1 \
    libglu1-mesa \
    libxext6 \
    libsm6 \
    libice6 \
    dbus-x11 \
    libglib2.0-0 \
    libmagic-mgc \
    libmagic1 \
    libxrender1 \
    libxrender-dev \
    libopenblas-dev \
    liblapack-dev \
    software-properties-common \
    curl \
    qtbase5-dev \
    qttools5-dev \
    qtcreator \
    pyqt5-dev-tools \
    libqt5core5a \
    python3-dev \
    python3-pip \
    python3-venv \
    python3-pytest-cov \
    python3-rosdep \
    python3-gz-transport13 \
    ros-dev-tools \
    vim \
    xclip \
    zstd \
    && rm -rf /var/lib/apt/lists/*


#TOTEST
# #############################
# # Setting up environment
# #############################
# Add uv to PATH
#ENV PATH="/root/.local/bin/:$PATH"
#WORKDIR /ros2_ws
## Create uv virtual environment and install dependencies
#RUN uv venv --python 3.9 --system-site-packages
#RUN . .venv/bin/activate
#RUN pip install -U pip argcomplete setuptools==58.2.0 bloom colcon-common-extensions rosdep vcstool lark numpy==1.23.4 scipy==1.11.1 torch torchvision PyQt5 opencv-python h5py tqdm gym==0.17.3 typed-argument-parser==1.10.0 einops termcolor==2.4.0 GitPython==3.1.37 matplotlib==3.7.2 pybullet==3.2.5 colorama==0.4.6 pandas imageio wandb==0.14.2
# why setuptools 80.7.1 does not work? #https://robotics.stackexchange.com/questions/101255/setuptoolsdeprecationwarning-setup-py-install-is-deprecated-use-build-and-pip
# pip list --verbose #see all installed packages


#####################################
# ROS2 Environment Setup and entrypoint
#####################################
### Adding all the necessary ros sourcing
RUN echo "" >> ~/.bashrc
RUN echo "## ROS2" >> ~/.bashrc
RUN echo 'source /opt/ros/${ROS_DISTRO}/setup.bash' >> ~/.bashrc

#TOTEST
# RUN echo 'source /ros2_ws/.venv/bin/activate' >> ~/.bashrc
# ### Setting up and calling the entrypoint
# RUN echo '#!/usr/bin/env bash' > /ros_entrypoint.sh
# RUN echo 'source $HOME/.bashrc' >> /ros_entrypoint.sh
# RUN echo 'exec "$@"' >> /ros_entrypoint.sh
# RUN chmod +x /ros_entrypoint.sh
# ENTRYPOINT ["/ros_entrypoint.sh"]

